# Import all the necessary components from syqlorix
from syqlorix import (
    doc, Component,
    head, body, title, meta, link, style, script,
    h1, p, div, a, img, br, code 
)

# --- Define a reusable component for the footer ---
# This demonstrates how to create clean, reusable parts for your UI.
class Footer(Component):
    def __init__(self):
        super().__init__(
            div(
                p("Generated by Syqlorix v0.2.1 ✨"),
                a("Check out the source on GitHub", href="https://github.com/Syqlorix/Syqlorix"),
                style_="text-align: center; margin-top: 50px; font-family: sans-serif; color: #aaa;"
            )
        )

# --- Define your main CSS styles as a multiline string ---
# These styles are embedded directly into the HTML head.
main_css = """
body {
    background-color: #1a1a2e;
    color: #e0e0e0;
    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
    line-height: 1.6;
    margin: 0;
    padding: 2rem;
}
h1 {
    color: #00a8cc;
    text-shadow: 0 0 5px #00a8cc;
}
a {
    color: #feda6a;
    text-decoration: none;
    transition: color 0.2s;
}
a:hover {
    color: #ffffff;
}
.container {
    max-width: 800px;
    margin: auto;
    background-color: #16213e;
    padding: 2rem;
    border-radius: 10px;
    box-shadow: 0 0 20px rgba(0,0,0,0.5);
    text-align: center;
}
.logo {
    max-width: 100px;
    margin-bottom: 1rem;
}
"""

# --- Define your JavaScript for interactivity ---
# This script is also embedded directly into the HTML.
interactive_js = """
document.addEventListener('DOMContentLoaded', () => {
    const heading = document.querySelector('h1');
    let clicks = 0;
    const originalText = heading.innerText;

    heading.addEventListener('click', () => {
        clicks++;
        heading.innerText = `${originalText} (Clicked ${clicks} times!)`;
    });

    console.log('Syqlorix page loaded and is interactive.');
});
"""

# --- Build the document using the futuristic '/' operator for nesting ---
# This is the main assembly of your webpage.
doc / head(
    title("Syqlorix - The Future is Now"),
    meta(charset="UTF-8"),
    meta(name="viewport", content="width=device-width, initial-scale=1.0"),

    # Link to an external stylesheet in the 'static' folder
    link(rel="stylesheet", href="/custom.css"),

    # Embed main styles directly in the head
    style(main_css)

) / body(
    div(
        # Link to a static image in the 'static' folder
        img(src_="/syqlorix-logo.svg", alt="Syqlorix Logo", class_="logo"),

        h1("Welcome to the Next Level"),
        p("Live reload and static file serving are fully operational."),
        p(
            "Try editing this file, or the CSS in ",
            code("static/custom.css"),
            " to see changes in real-time."
        ),
        class_="container" # Use class_ for CSS classes
    ),
    Footer(), # Use our reusable component
    script(interactive_js) # Add our interactive JavaScript
)

# No `if __name__ == "__main__"` block is needed.