# Import all the necessary components from syqlorix
from syqlorix import (
    doc, Component,
    head, body, title, meta, link, style, script,
    h1, p, div, a, img, br, code
)

# ---------------------------------------------------------
# 1.  Re-usable Footer component
# ---------------------------------------------------------
class Footer(Component):
    def __init__(self):
        super().__init__(
            div(
                p("Generated by Syqlorix v1.1.30 ✨"),
                a("Check out the source on GitHub",
                  href="https://github.com/Syqlorix/Syqlorix"),
                style_="text-align: center; margin-top: 50px; font-family: sans-serif; color: #aaa;"
            )
        )

# ---------------------------------------------------------
# 2.  Embedded CSS (no external file needed for this demo)
# ---------------------------------------------------------
main_css = """
body {
    background-color: #1a1a2e;
    color: #e0e0e0;
    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
    line-height: 1.6;
    margin: 0;
    padding: 2rem;
}
h1 {
    color: #00a8cc;
    text-shadow: 0 0 5px #00a8cc;
}
a {
    color: #feda6a;
    text-decoration: none;
    transition: color 0.2s;
}
a:hover {
    color: #ffffff;
}
.container {
    max-width: 800px;
    margin: auto;
    background-color: #16213e;
    padding: 2rem;
    border-radius: 10px;
    box-shadow: 0 0 20px rgba(0,0,0,0.5);
    text-align: center;
}
.logo {
    max-width: 100px;
    margin-bottom: 1rem;
}
"""

# ---------------------------------------------------------
# 3.  Tiny interactive JavaScript (embedded)
# ---------------------------------------------------------
interactive_js = """
document.addEventListener('DOMContentLoaded', () => {
    const heading = document.querySelector('h1');
    let clicks = 0;
    const originalText = heading.innerText;

    heading.addEventListener('click', () => {
        clicks++;
        heading.innerText = `${originalText} (Clicked ${clicks} times!)`;
    });

    console.log('Syqlorix page loaded and is interactive.');
});
"""

# ---------------------------------------------------------
# 4.  Build the page tree with the handy '/' operator
# ---------------------------------------------------------
doc / head(
    title("Syqlorix - The Future is Now"),
    meta(charset="UTF-8"),
    meta(name="viewport", content="width=device-width, initial-scale=1.0"),
    style(main_css)
) / body(
    div(
        img(
            src_="/syqlorix-logo.svg",
            alt="Syqlorix Logo",
            class_="logo"
        ),
        h1("Welcome to the Next Level"),
        p("Live reload and static file serving are fully operational."),
        p(
            "Try editing this file, or the CSS in ",
            code("static/custom.css"),
            " to see changes in real-time."
        ),
        class_="container"
    ),
    Footer(),
    script(interactive_js)
)

# ---------------------------------------------------------
# 5.  EXPOSE the page on the root route so it actually renders
# ---------------------------------------------------------
@doc.route('/')
def home_page(request):
    return doc